
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: dd-prototype-development
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: http-bymyelectrics-com-22b5b2ac
      hostname: "bymyelectrics.com"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-cecinasmarcelina-com-05f27d2b
      hostname: "cecinasmarcelina.com"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-healthcare-nexodev-org-0b03b8da
      hostname: "healthcare.nexodev.org"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-vitaintegral-nexodev-org-3553461d
      hostname: "vitaintegral.nexodev.org"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-www-bymyelectrics-com-a4eb7a1f
      hostname: "www.bymyelectrics.com"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-www-cecinasmarcelina-com-78e6abc3
      hostname: "www.cecinasmarcelina.com"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
