const DefaultConf = /**/ {
  client: {
    dogmadual: {
      metadata: { title: 'DOGMADUAL.com' },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'SearchBox',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Pagination',
          'windowGetDimensions',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'PublicProfile',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
        ],
        dogmadual: [
          'MenuDogmadual',
          'RoutesDogmadual',
          'ElementsDogmadual',
          'CommonDogmadual',
          'CssDogmadual',
          'LogInDogmadual',
          'LogOutDogmadual',
          'SignUpDogmadual',
          'SocketIoDogmadual',
          'SettingsDogmadual',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/settings', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/log-in', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/sign-up', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/log-out', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/account', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/recover', client: 'Dogmadual', ssr: 'Dogmadual' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
      ],
      services: ['core', 'file', 'user'],
    },
    nexodev: {
      metadata: {
        title: 'Nexodev - ERP, CRM Development & Cloud DevOps Services',
        description:
          'Nexodev specializes in developing and implementing robust ERP & CRM systems, along with providing expert cloud DevOps services. We empower businesses to streamline operations and achieve strategic goals.',
        keywords: [
          'ERP development',
          'CRM development',
          'cloud DevOps',
          'ERP implementation',
          'CRM implementation',
          'business process automation',
          'enterprise resource planning',
          'customer relationship management',
          'cloud infrastructure',
          'IT automation',
        ],
        author: 'https://github.com/underpostnet',
        baseBuildIconReference: './src/client/public/nexodev/assets/logo/nexodev-purple-t.png',
        thumbnail: 'assets/banner/nexodev.jpg',
        themeColor: '#69055F',
        backgroundImage: 'assets/background/white-purple-2.jpg',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'SearchBox',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Pagination',
          'windowGetDimensions',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'PublicProfile',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
          'Panel',
          'PanelForm',
        ],
        chart: ['connectedScatterplotChart'],
        nexodev: [
          'MenuNexodev',
          'RoutesNexodev',
          'ElementsNexodev',
          'CommonNexodev',
          'CssNexodev',
          'LogInNexodev',
          'LogOutNexodev',
          'SignUpNexodev',
          'CalendarNexodev',
          'DashboardNexodev',
          'StreamNexodev',
          'SocketIoNexodev',
          'SettingsNexodev',
        ],
      },
      views: [
        { path: '/', title: 'ERP, CRM Development & Cloud DevOps Services', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/blog', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/settings', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/log-in', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/sign-up', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/log-out', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/account', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/calendar', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/dashboard', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/stream', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/docs', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/content', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/cloud', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/chat', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/settings', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/wallet', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/recover', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/default-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/user-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/instance-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/cron-management', client: 'Nexodev', ssr: 'Nexodev' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/easymde/dist', public_folder: '/dist/easymde' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        { folder: './node_modules/d3/dist', public_folder: '/dist/d3' },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
        {
          folder: './node_modules/marked/lib',
          public_folder: '/dist/marked',
          import_name: 'marked',
          import_name_build: '/dist/marked/marked.esm.js',
        },
        { folder: './node_modules/@fullcalendar', public_folder: '/dist/@fullcalendar' },
        { folder: './node_modules/rrule/dist/es5', public_folder: '/dist/rrule' },
      ],
      services: ['default', 'core', 'user', 'document', 'file', 'crypto', 'instance', 'event-scheduler', 'cron'],
    },
    healthcare: {
      metadata: {
        title: 'Healthcare - ERP CRM Nexodev',
        description:
          'Revolutionize healthcare operations with our integrated ERP and CRM solution. Streamline patient management, optimize workflows, and enhance decision-making.',
        keywords: [
          'healthcare ERP',
          'healthcare CRM',
          'medical practice management',
          'patient management',
          'workflow automation',
          'healthcare IT',
        ],
        author: 'https://healthcare.nexodev.org',
        thumbnail: 'assets/logo/base-icon.png',
        themeColor: '#fffcf9',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'SearchBox',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Pagination',
          'windowGetDimensions',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'PublicProfile',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Panel',
          'Recover',
          'PanelForm',
        ],
        chart: ['connectedScatterplotChart'],
        healthcare: [
          'MenuHealthcare',
          'RoutesHealthcare',
          'ElementsHealthcare',
          'CommonHealthcare',
          'CssHealthcare',
          'LogInHealthcare',
          'LogOutHealthcare',
          'SignUpHealthcare',
          'CalendarHealthcare',
          'SocketIoHealthcare',
          'SettingsHealthcare',
          'TranslateHealthcare',
          'AppointmentFormHealthCare',
          'RecordMoodHealthcare',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/settings', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/log-in', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/sign-up', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/log-out', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/account', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/settings', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/recover', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/nutrition-tips', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/calendar', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/healthcare-appointment', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/healthcare-appointment-management', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/record-mood', client: 'Healthcare', ssr: 'Healthcare' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/easymde/dist', public_folder: '/dist/easymde' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        { folder: './node_modules/d3/dist', public_folder: '/dist/d3' },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
        {
          folder: './node_modules/marked/lib',
          public_folder: '/dist/marked',
          import_name: 'marked',
          import_name_build: '/dist/marked/marked.esm.js',
        },
        { folder: './node_modules/@fullcalendar', public_folder: '/dist/@fullcalendar' },
        { folder: './node_modules/rrule/dist/es5', public_folder: '/dist/rrule' },
      ],
      services: ['core', 'user', 'document', 'file', 'event-scheduler', 'healthcare-appointment', 'default'],
    },
    bymyelectrics: {
      metadata: {
        title: 'Bymyelectrics - Streamline Industrial Electrical Services with a Powerful ERP',
        description:
          'Boost efficiency and profitability with a dedicated ERP for industrial electrical services. Manage projects, inventory, maintenance, and more from a single platform.',
        keywords: [
          'industrial electrical services ERP',
          'electrical services management software',
          'field service management for electricians',
          'electrical contractor ERP',
          'maintenance management software',
          'project management for electrical contractors',
          'inventory management for electrical services',
          'electrical service scheduling',
          'work order management',
          'electrical compliance',
          'electrical safety',
        ],
        author: 'https://www.bymylectrics.com',
        thumbnail: 'assets/social.png',
        themeColor: '#ffffff',
        backgroundImage: null,
        pwaAssetsPath: '',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'SearchBox',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Pagination',
          'windowGetDimensions',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'PublicProfile',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
          '404',
          '500',
          'Alert',
        ],
        bymyelectrics: [
          'MenuBymyelectrics',
          'RoutesBymyelectrics',
          'ElementsBymyelectrics',
          'CommonBymyelectrics',
          'CssBymyelectrics',
          'LogInBymyelectrics',
          'LogOutBymyelectrics',
          'SignUpBymyelectrics',
          'SocketIoBymyelectrics',
          'SettingsBymyelectrics',
          'TranslateBymyelectrics',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/settings', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/log-in', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/sign-up', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/log-out', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/account', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/wallet', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/recover', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/default-management', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { client: 'Bymyelectrics', ssr: 'Bymyelectrics', path: '/404', title: '404 Not Found' },
        { client: 'Bymyelectrics', ssr: 'Bymyelectrics', path: '/500', title: '500 Server Error' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
      ],
      services: ['core', 'user', 'file', 'crypto', 'default'],
    },
  },
  ssr: {
    Nexodev: {
      head: ['Seo', 'Pwa', 'NexodevScripts', 'Css'],
      body: ['CacheControl', 'NexodevSplashScreen', 'SwaggerDarkMode'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Dogmadual: {
      head: ['DogmadualScripts', 'Css'],
      body: ['CacheControl', 'DefaultSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Healthcare: {
      head: ['Seo', 'PwaHealthcare', 'HealthcareScripts', 'Css'],
      body: ['CacheControl', 'HealthcareSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Bymyelectrics: {
      head: ['Seo', 'PwaBymyelectrics', 'BymyelectricsScripts', 'Css'],
      body: ['CacheControl', 'BymyelectricsSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
  },
  server: {
    'dogmadual.com': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        proxy: [80, 443],
        redirect: 'https://www.dogmadual.com',
      },
    },
    'www.dogmadual.com': {
      '/': {
        client: 'dogmadual',
        runtime: 'nodejs',
        apis: ['user', 'file'],
        origins: [],
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'env:DB_HOST', name: 'env:DB_NAME_DOGMADUAL' },
        valkey: { port: 'env:VALKEY_PORT', host: 'env:VALKEY_HOST' },
        mailer: {
          sender: { email: 'env:MAILER_SENDER_EMAIL', name: 'env:MAILER_SENDER_NAME' },
          transport: {
            host: 'env:SMTP_HOST',
            port: 'env:SMTP_PORT',
            secure: true,
            auth: { user: 'env:SMTP_AUTH_USER', pass: 'env:SMTP_AUTH_PASS' },
          },
        },
      },
    },
    'nexodev.org': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        proxy: [80, 443],
        redirect: 'https://www.nexodev.org',
      },
    },
    'www.nexodev.org': {
      '/': {
        client: 'nexodev',
        runtime: 'nodejs',
        apis: ['default', 'user', 'test', 'document', 'file', 'crypto', 'instance', 'event-scheduler', 'cron', 'core'],
        origins: ['https://www.nexodev.org', 'https://underpost.net', 'https://underpostnet.github.io'],
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'env:DB_HOST', name: 'env:DB_NAME_NEXODEV' },
        valkey: { port: 'env:VALKEY_PORT', host: 'env:VALKEY_HOST' },
        mailer: {
          sender: { email: 'env:MAILER_SENDER_EMAIL', name: 'env:MAILER_SENDER_NAME' },
          transport: {
            host: 'env:SMTP_HOST',
            port: 'env:SMTP_PORT',
            secure: true,
            auth: { user: 'env:SMTP_AUTH_USER', pass: 'env:SMTP_AUTH_PASS' },
          },
        },
      },
    },
    'healthcare.nexodev.org': {
      '/': {
        client: 'healthcare',
        runtime: 'nodejs',
        apis: ['user', 'test', 'document', 'file', 'event-scheduler', 'healthcare-appointment', 'default'],
        origins: [],
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'env:DB_HOST', name: 'env:DB_NAME_HEALTHCARE' },
        valkey: { port: 'env:VALKEY_PORT', host: 'env:VALKEY_HOST' },
        mailer: {
          sender: { email: 'env:MAILER_SENDER_EMAIL', name: 'env:MAILER_SENDER_NAME' },
          transport: {
            host: 'env:SMTP_HOST',
            port: 'env:SMTP_PORT',
            secure: true,
            auth: { user: 'env:SMTP_AUTH_USER', pass: 'env:SMTP_AUTH_PASS' },
          },
        },
      },
    },
    'www.bymyelectrics.com': {
      '/': {
        client: 'bymyelectrics',
        runtime: 'nodejs',
        apis: ['user', 'file', 'crypto', 'default'],
        origins: [],
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'env:DB_HOST', name: 'env:DB_NAME_BYMYELECTRICS' },
        valkey: { port: 'env:VALKEY_PORT', host: 'env:VALKEY_HOST' },
        mailer: {
          sender: { email: 'env:MAILER_SENDER_EMAIL', name: 'env:MAILER_SENDER_NAME' },
          transport: {
            host: 'env:SMTP_HOST',
            port: 'env:SMTP_PORT',
            secure: true,
            auth: { user: 'env:SMTP_AUTH_USER', pass: 'env:SMTP_AUTH_PASS' },
          },
        },
      },
    },
    'bymyelectrics.com': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        proxy: [80, 443],
        redirect: 'https://www.bymyelectrics.com',
      },
    },
    'vitaintegral.nexodev.org': {
      '/': {
        client: 'healthcare',
        runtime: 'nodejs',
        apis: ['user', 'test', 'document', 'file', 'event-scheduler', 'healthcare-appointment', 'default'],
        origins: [],
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'env:DB_HOST', name: 'env:DB_NAME_HEALTHCARE' },
        valkey: { port: 'env:VALKEY_PORT', host: 'env:VALKEY_HOST' },
        mailer: {
          sender: { email: 'env:MAILER_SENDER_EMAIL', name: 'env:MAILER_SENDER_NAME' },
          transport: {
            host: 'env:SMTP_HOST',
            port: 'env:SMTP_PORT',
            secure: true,
            auth: { user: 'env:SMTP_AUTH_USER', pass: 'env:SMTP_AUTH_PASS' },
          },
        },
      },
    },
  },
  cron: {
    records: {
      A: [
        {
          host: 'env:DDNS_HOST:example.com',
          dns: 'env:DDNS_PROVIDER:dondominio',
          api_key: 'env:DDNS_API_KEY:',
          user: 'env:DDNS_USER:',
        },
      ],
    },
    jobs: {
      dns: { expression: '* * * * *', enabled: true, instances: 1 },
      backups: { expression: '0 1 * * *', enabled: true, instances: 1 },
    },
  },
}; /**/

export { DefaultConf };
