import dotenv from 'dotenv';

dotenv.config();

const DefaultConf = /**/ {
  client: {
    underpost: {
      metadata: {
        title: 'underpost.net - Technological and Cultural Lab',
        description:
          'Explore the intersection of technology and culture with in-depth articles, projects, and discussions.',
        keywords: ['tech blog', 'cultural lab', 'technology', 'culture', 'innovation'],
        author: 'https://github.com/underpostnet',
        thumbnail: 'assets/banner/underpost-social.jpg',
        themeColor: '#141414',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
          'Panel',
          'PanelForm',
        ],
        underpost: [
          'MenuUnderpost',
          'RoutesUnderpost',
          'ElementsUnderpost',
          'CommonUnderpost',
          'CssUnderpost',
          'LogInUnderpost',
          'LogOutUnderpost',
          'SignUpUnderpost',
          'LabGalleryUnderpost',
          'CyberpunkBloggerUnderpost',
          'TranslateUnderpost',
          'SocketIoUnderpost',
          'SettingsUnderpost',
        ],
      },
      views: [
        { path: '/', title: 'Technological and Cultural Lab', client: 'Underpost', ssr: 'Underpost' },
        { path: '/lab-gallery', client: 'Underpost', ssr: 'Underpost' },
        { path: '/contracultura-cyberpunk', client: 'Underpost', ssr: 'Underpost' },
        { path: '/settings', client: 'Underpost', ssr: 'Underpost' },
        { path: '/log-in', client: 'Underpost', ssr: 'Underpost' },
        { path: '/sign-up', client: 'Underpost', ssr: 'Underpost' },
        { path: '/log-out', client: 'Underpost', ssr: 'Underpost' },
        { path: '/account', client: 'Underpost', ssr: 'Underpost' },
        { path: '/recover', client: 'Underpost', ssr: 'Underpost' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/@loadingio/css-spinner/entries', public_folder: '/dist/loadingio' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.auto.complete.esm.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
        { folder: './node_modules/easymde/dist', public_folder: '/dist/easymde' },
        {
          folder: './node_modules/marked/lib',
          public_folder: '/dist/marked',
          import_name: 'marked',
          import_name_build: '/dist/marked/marked.esm.js',
        },
      ],
      services: ['core', 'user', 'file', 'test', 'document'],
    },
    cryptokoyn: {
      metadata: { title: 'Cryptokoyn' },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
        ],
        cryptokoyn: [
          'MenuCryptokoyn',
          'RoutesCryptokoyn',
          'ElementsCryptokoyn',
          'CommonCryptokoyn',
          'CssCryptokoyn',
          'LogInCryptokoyn',
          'LogOutCryptokoyn',
          'SignUpCryptokoyn',
          'SocketIoCryptokoyn',
          'SettingsCryptokoyn',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
        { path: '/settings', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
        { path: '/log-in', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
        { path: '/sign-up', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
        { path: '/log-out', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
        { path: '/account', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
        { path: '/wallet', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
        { path: '/recover', client: 'Cryptokoyn', ssr: 'Cryptokoyn' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/@loadingio/css-spinner/entries', public_folder: '/dist/loadingio' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.auto.complete.esm.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
      ],
      services: ['core', 'user', 'file', 'crypto'],
    },
    dogmadual: {
      metadata: { title: 'DOGMADUAL.com' },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
        ],
        dogmadual: [
          'MenuDogmadual',
          'RoutesDogmadual',
          'ElementsDogmadual',
          'CommonDogmadual',
          'CssDogmadual',
          'LogInDogmadual',
          'LogOutDogmadual',
          'SignUpDogmadual',
          'SocketIoDogmadual',
          'SettingsDogmadual',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/settings', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/log-in', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/sign-up', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/log-out', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/account', client: 'Dogmadual', ssr: 'Dogmadual' },
        { path: '/recover', client: 'Dogmadual', ssr: 'Dogmadual' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/@loadingio/css-spinner/entries', public_folder: '/dist/loadingio' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.auto.complete.esm.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
      ],
      services: ['core', 'file', 'user'],
    },
    nexodev: {
      metadata: {
        title: 'Nexodev - ERP, CRM Development & Cloud DevOps Services',
        description:
          'Nexodev specializes in developing and implementing robust ERP & CRM systems, along with providing expert cloud DevOps services. We empower businesses to streamline operations and achieve strategic goals.',
        keywords: [
          'ERP development',
          'CRM development',
          'cloud DevOps',
          'ERP implementation',
          'CRM implementation',
          'business process automation',
          'enterprise resource planning',
          'customer relationship management',
          'cloud infrastructure',
          'IT automation',
        ],
        author: 'https://github.com/underpostnet',
        thumbnail: 'assets/banner/nexodev.jpg',
        themeColor: '#69055F',
        backgroundImage: 'assets/background/earth-min.jpg',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
          'Panel',
          'PanelForm',
        ],
        chart: ['connectedScatterplotChart'],
        nexodev: [
          'MenuNexodev',
          'RoutesNexodev',
          'ElementsNexodev',
          'CommonNexodev',
          'CssNexodev',
          'LogInNexodev',
          'LogOutNexodev',
          'SignUpNexodev',
          'CalendarNexodev',
          'DashboardNexodev',
          'StreamNexodev',
          'SocketIoNexodev',
          'SettingsNexodev',
        ],
      },
      views: [
        { path: '/', title: 'ERP, CRM Development & Cloud DevOps Services', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/blog', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/settings', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/log-in', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/sign-up', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/log-out', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/account', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/calendar', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/dashboard', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/stream', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/docs', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/content', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/cloud', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/chat', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/settings', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/wallet', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/recover', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/default-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/user-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/instance-management', client: 'Nexodev', ssr: 'Nexodev' },
        { path: '/cron-management', client: 'Nexodev', ssr: 'Nexodev' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/@loadingio/css-spinner/entries', public_folder: '/dist/loadingio' },
        { folder: './node_modules/easymde/dist', public_folder: '/dist/easymde' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.auto.complete.esm.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        { folder: './node_modules/d3/dist', public_folder: '/dist/d3' },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
        {
          folder: './node_modules/marked/lib',
          public_folder: '/dist/marked',
          import_name: 'marked',
          import_name_build: '/dist/marked/marked.esm.js',
        },
        { folder: './node_modules/@fullcalendar', public_folder: '/dist/@fullcalendar' },
        { folder: './node_modules/rrule/dist/es5', public_folder: '/dist/rrule' },
      ],
      services: [
        'default',
        'core',
        'user',
        'document',
        'file',
        'crypto',
        'notification',
        'event',
        'bot',
        'user-group',
        'instance',
        'event-scheduler',
        'cron',
      ],
    },
    healthcare: {
      metadata: {
        title: 'Healthcare - ERP CRM Nexodev',
        description:
          'Revolutionize healthcare operations with our integrated ERP and CRM solution. Streamline patient management, optimize workflows, and enhance decision-making.',
        keywords: [
          'healthcare ERP',
          'healthcare CRM',
          'medical practice management',
          'patient management',
          'workflow automation',
          'healthcare IT',
        ],
        author: 'https://healthcare.nexodev.org',
        thumbnail: 'assets/logo/base-icon.png',
        themeColor: '#fffcf9',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Panel',
          'Recover',
          'PanelForm',
        ],
        chart: ['connectedScatterplotChart'],
        healthcare: [
          'MenuHealthcare',
          'RoutesHealthcare',
          'ElementsHealthcare',
          'CommonHealthcare',
          'CssHealthcare',
          'LogInHealthcare',
          'LogOutHealthcare',
          'SignUpHealthcare',
          'CalendarHealthcare',
          'DashboardHealthcare',
          'StreamHealthcare',
          'SocketIoHealthcare',
          'SettingsHealthcare',
          'TranslateHealthcare',
          'AppointmentFormHealthCare',
          'RecordMoodHealthcare',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/settings', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/log-in', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/sign-up', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/log-out', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/account', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/settings', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/recover', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/nutrition-tips', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/calendar', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/healthcare-appointment', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/healthcare-appointment-management', client: 'Healthcare', ssr: 'Healthcare' },
        { path: '/record-mood', client: 'Healthcare', ssr: 'Healthcare' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/@loadingio/css-spinner/entries', public_folder: '/dist/loadingio' },
        { folder: './node_modules/easymde/dist', public_folder: '/dist/easymde' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.auto.complete.esm.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        { folder: './node_modules/d3/dist', public_folder: '/dist/d3' },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
        {
          folder: './node_modules/marked/lib',
          public_folder: '/dist/marked',
          import_name: 'marked',
          import_name_build: '/dist/marked/marked.esm.js',
        },
        { folder: './node_modules/@fullcalendar', public_folder: '/dist/@fullcalendar' },
        { folder: './node_modules/rrule/dist/es5', public_folder: '/dist/rrule' },
      ],
      services: ['core', 'user', 'document', 'file', 'event-scheduler', 'healthcare-appointment', 'default'],
    },
    itemledger: {
      metadata: { title: 'Item Ledger' },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
        ],
        itemledger: [
          'MenuItemledger',
          'RoutesItemledger',
          'ElementsItemledger',
          'CommonItemledger',
          'CssItemledger',
          'LogInItemledger',
          'LogOutItemledger',
          'SignUpItemledger',
          'SocketIoItemledger',
          'SettingsItemledger',
          'TranslateItemledger',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Itemledger', ssr: 'Itemledger' },
        { path: '/settings', client: 'Itemledger', ssr: 'Itemledger' },
        { path: '/log-in', client: 'Itemledger', ssr: 'Itemledger' },
        { path: '/sign-up', client: 'Itemledger', ssr: 'Itemledger' },
        { path: '/log-out', client: 'Itemledger', ssr: 'Itemledger' },
        { path: '/account', client: 'Itemledger', ssr: 'Itemledger' },
        { path: '/wallet', client: 'Itemledger', ssr: 'Itemledger' },
        { path: '/recover', client: 'Itemledger', ssr: 'Itemledger' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/@loadingio/css-spinner/entries', public_folder: '/dist/loadingio' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.auto.complete.esm.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
      ],
      services: ['core', 'user', 'file', 'crypto', 'default'],
    },
    bymyelectrics: {
      metadata: {
        title: 'Bymyelectrics - Streamline Industrial Electrical Services with a Powerful ERP',
        description:
          'Boost efficiency and profitability with a dedicated ERP for industrial electrical services. Manage projects, inventory, maintenance, and more from a single platform.',
        keywords: [
          'industrial electrical services ERP',
          'electrical services management software',
          'field service management for electricians',
          'electrical contractor ERP',
          'maintenance management software',
          'project management for electrical contractors',
          'inventory management for electrical services',
          'electrical service scheduling',
          'work order management',
          'electrical compliance',
          'electrical safety',
        ],
        author: 'https://www.bymylectrics.com',
        thumbnail: 'assets/social.png',
        themeColor: '#ffffff',
        backgroundImage: null,
        pwaAssetsPath: '',
      },
      components: {
        core: [
          'CommonJs',
          'VanillaJs',
          'Responsive',
          'Keyboard',
          'Translate',
          'Modal',
          'BtnIcon',
          'Logger',
          'Css',
          'NotificationManager',
          'ToggleSwitch',
          'DropDown',
          'LoadingAnimation',
          'EventsUI',
          'AgGrid',
          'Input',
          'Validator',
          'SignUp',
          'LogIn',
          'LogOut',
          'Router',
          'Account',
          'Scroll',
          'Auth',
          'FullScreen',
          'RichText',
          'CalendarCore',
          'D3Chart',
          'Stream',
          'SocketIo',
          'Docs',
          'Content',
          'FileExplorer',
          'Chat',
          'Worker',
          'CssCore',
          'Wallet',
          'Badge',
          'ToolTip',
          'Webhook',
          'Recover',
          '404',
          '500',
          'Alert',
        ],
        bymyelectrics: [
          'MenuBymyelectrics',
          'RoutesBymyelectrics',
          'ElementsBymyelectrics',
          'CommonBymyelectrics',
          'CssBymyelectrics',
          'LogInBymyelectrics',
          'LogOutBymyelectrics',
          'SignUpBymyelectrics',
          'SocketIoBymyelectrics',
          'SettingsBymyelectrics',
          'TranslateBymyelectrics',
        ],
      },
      views: [
        { path: '/', title: 'Home', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/settings', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/log-in', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/sign-up', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/log-out', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/account', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/wallet', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/recover', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { path: '/default-management', client: 'Bymyelectrics', ssr: 'Bymyelectrics' },
        { client: 'Bymyelectrics', ssr: 'Bymyelectrics', path: '/404', title: '404 Not Found' },
        { client: 'Bymyelectrics', ssr: 'Bymyelectrics', path: '/500', title: '500 Server Error' },
      ],
      dists: [
        {
          folder: './node_modules/@neodrag/vanilla/dist/min',
          public_folder: '/dist/@neodrag-vanilla',
          import_name: '@neodrag/vanilla',
          import_name_build: '/dist/@neodrag-vanilla/index.js',
        },
        { folder: './node_modules/@fortawesome/fontawesome-free', public_folder: '/dist/fontawesome' },
        {
          folder: './node_modules/sortablejs/modular',
          public_folder: '/dist/sortablejs',
          import_name: 'sortablejs',
          import_name_build: '/dist/sortablejs/sortable.complete.esm.js',
        },
        { folder: './node_modules/validator', public_folder: '/dist/validator' },
        { folder: './node_modules/@loadingio/css-spinner/entries', public_folder: '/dist/loadingio' },
        {
          import_name: 'ag-grid-community',
          import_name_build: '/dist/ag-grid-community/ag-grid-community.auto.complete.esm.min.js',
          folder: './node_modules/ag-grid-community/dist',
          public_folder: '/dist/ag-grid-community',
          styles: './node_modules/ag-grid-community/styles',
          public_styles_folder: '/styles/ag-grid-community',
        },
        {
          folder: './node_modules/socket.io/client-dist',
          public_folder: '/dist/socket.io',
          import_name: 'socket.io/client-dist/socket.io.esm.min.js',
          import_name_build: '/dist/socket.io/socket.io.esm.min.js',
        },
        { folder: './node_modules/peerjs/dist', public_folder: '/dist/peerjs' },
      ],
      services: ['core', 'user', 'file', 'crypto', 'default'],
    },
  },
  ssr: {
    Nexodev: {
      head: ['Seo', 'Pwa', 'NexodevScripts', 'Css'],
      body: ['CacheControl', 'NexodevSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Dogmadual: {
      head: ['DogmadualScripts', 'Css'],
      body: ['CacheControl', 'DefaultSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Cryptokoyn: {
      head: ['CryptokoynScripts', 'Css'],
      body: ['CacheControl', 'DefaultSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Underpost: {
      head: ['Seo', 'Pwa', 'UnderpostScripts', 'Css'],
      body: ['CacheControl', 'UnderpostDefaultSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Healthcare: {
      head: ['Seo', 'PwaHealthcare', 'HealthcareScripts', 'Css'],
      body: ['CacheControl', 'HealthcareSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Itemledger: {
      head: ['ItemledgerScripts', 'Css'],
      body: ['CacheControl', 'DefaultSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
    Bymyelectrics: {
      head: ['Seo', 'PwaBymyelectrics', 'BymyelectricsScripts', 'Css'],
      body: ['CacheControl', 'BymyelectricsSplashScreen'],
      mailer: { userVerifyEmail: 'DefaultVerifyEmail', userRecoverEmail: 'DefaultRecoverEmail' },
      offline: [
        { path: '/offline', title: 'No Network Connection', client: 'NoNetworkConnection', head: [], body: [] },
        { path: '/maintenance', title: 'Server Maintenance', client: 'Maintenance', head: [], body: [] },
      ],
      pages: [{ path: '/test', title: 'Test', client: 'Test', head: [], body: [] }],
    },
  },
  server: {
    'underpost.net': {
      '/': {
        client: 'underpost',
        runtime: 'nodejs',
        apis: ['user', 'file', 'test', 'document'],
        apiBaseProxyPath: '/',
        apiBaseHost: 'www.nexodev.org',
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'www.underpost.net': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        proxy: [80, 443],
        redirect: 'https://underpost.net',
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'cryptokoyn.net': {
      '/': {
        client: 'cryptokoyn',
        runtime: 'nodejs',
        apis: ['user', 'file', 'crypto'],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'www.cryptokoyn.net': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        proxy: [80, 443],
        redirect: 'https://cryptokoyn.net',
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'dogmadual.com': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        proxy: [80, 443],
        redirect: 'https://www.dogmadual.com',
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'www.dogmadual.com': {
      '/': {
        client: 'dogmadual',
        runtime: 'nodejs',
        apis: ['user', 'file'],
        origins: [],
        ws: 'core',
        peer: true,
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'nexodev.org': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        proxy: [80, 443],
        redirect: 'https://www.nexodev.org',
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'www.nexodev.org': {
      '/': {
        client: 'nexodev',
        runtime: 'nodejs',
        apis: [
          'default',
          'user',
          'test',
          'document',
          'file',
          'crypto',
          'notification',
          'event',
          'bot',
          'user-group',
          'instance',
          'event-scheduler',
          'cron',
          'core',
        ],
        origins: ['https://www.nexodev.org', 'https://underpost.net', 'https://underpostnet.github.io'],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: true,
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'healthcare.nexodev.org': {
      '/': {
        client: 'healthcare',
        runtime: 'nodejs',
        apis: ['user', 'test', 'document', 'file', 'event-scheduler', 'healthcare-appointment', 'default'],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        iconsBuild: false,
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'itemledger.com': {
      '/': {
        client: 'itemledger',
        runtime: 'nodejs',
        apis: ['user', 'file', 'crypto'],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        iconsBuild: false,
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'www.itemledger.com': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        proxy: [80, 443],
        redirect: 'https://itemledger.com',
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'www.bymyelectrics.com': {
      '/': {
        client: 'bymyelectrics',
        runtime: 'nodejs',
        apis: ['user', 'file', 'crypto', 'default'],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        iconsBuild: false,
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'bymyelectrics.com': {
      '/': {
        client: null,
        runtime: 'nodejs',
        apis: [],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        proxy: [80, 443],
        redirect: 'https://www.bymyelectrics.com',
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
    'vitaintegral.nexodev.org': {
      '/': {
        client: 'healthcare',
        runtime: 'nodejs',
        apis: ['user', 'test', 'document', 'file', 'event-scheduler', 'healthcare-appointment', 'default'],
        origins: [],
        minifyBuild: false,
        liteBuild: true,
        docsBuild: false,
        iconsBuild: false,
        ws: 'core',
        peer: true,
        proxy: [80, 443],
        db: { provider: 'mongoose', host: 'mongodb://127.0.0.1:27017', name: 'default' },
        valkey: { port: 6379, host: '127.0.0.1' },
        mailer: {
          sender: { email: 'noreply@default.net', name: 'Default' },
          transport: {
            host: 'smtp.default.com',
            port: 465,
            secure: true,
            auth: { user: 'noreply@default.net', pass: '' },
          },
        },
      },
    },
  },
  cron: {
    records: { A: [{ host: 'example.com', dns: 'dondominio', api_key: '???', user: '???' }] },
    jobs: { dns: { expression: '* * * * *', enabled: true }, backups: { expression: '0 1 * * *', enabled: true } },
  },
}; /**/

export { DefaultConf };
