apiVersion: v1
kind: Pod
metadata:
  name: "underpost-engine"
spec:
  containers:
    - name: "underpost-engine"
      image: "underpost-engine:latest"
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      imagePullPolicy: Never
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 22
          hostPort: 22
        - containerPort: 5500
          hostPort: 5500
        - containerPort: 5501
          hostPort: 5501
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "shared"
      effect: "NoSchedule"
  # tolerationSeconds: 18000
  # imagePullSecrets:
  #   - name: my-secret
