apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: 'mariadb'
            - name: PMA_PORT
              value: '3306'
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: UPLOAD_LIMIT
              value: '300M'
            - name: PMA_ARBITRARY
              value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      nodePort: 31008
      port: 80
      targetPort: 80
