apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            # - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongodb-secret
            #       key: username
            # - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongodb-secret
            #       key: password
            - name: ME_CONFIG_SITE_BASEURL
              value: '/mongo/'
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: ME_CONFIG_MONGODB_SERVER
              value: 'mongodb-0.mongodb-service'
            # - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            #   value: 'true'
            - name: ME_CONFIG_MONGODB_PORT
              value: '27017'
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
