apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
    group: db
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      protocol: TCP
      port: 8081
      targetPort: 8081
