
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.giancarlobertini.com
spec:
  virtualhost:
    fqdn: www.giancarlobertini.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-lampp-development-blue-service
          port: 4001
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: giancarlobertini.com
spec:
  virtualhost:
    fqdn: giancarlobertini.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-lampp-development-blue-service
          port: 4002
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: www.ayleenbertini.com
spec:
  virtualhost:
    fqdn: www.ayleenbertini.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-lampp-development-blue-service
          port: 4003
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ayleenbertini.com
spec:
  virtualhost:
    fqdn: ayleenbertini.com
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: dd-lampp-development-blue-service
          port: 4004
          weight: 100
    