config:
  limits.cpu: "2"
  limits.memory: 4GB
description: vm nat network
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
    ipv4.address: 10.250.250.100
  root:
    path: /
    pool: local # lxc storage list
    size: 100GB
    type: disk
name: admin-profile
used_by: []
