apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      hostname: mongo
      containers:
        - name: mongodb
          image: docker.io/library/mongo:4.4
          command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db

          resources:
            requests:
              memory: '500Mi'
              cpu: '500m'
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
