/**
 * Kickstart configuration generator for Underpost Engine
 * This module provides a factory function to generate a kickstart configuration string
 * tailored for use in an Anaconda installer environment.
 * @module src/cli/kickstart.js
 * @namespace UnderpostKickStart
 */

import fs from 'fs';

/**
 * @class UnderpostKickStart
 * @description
 * This class provides a static API for generating kickstart configuration strings
 * for use in the Underpost Engine's ephemeral commissioning process. The generated
 * kickstart is designed to run in an Anaconda installer environment with inst.sshd
 * enabled, allowing for SSH access during the installation process.
 * @memberof UnderpostKickStart
 */
class UnderpostKickStart {
  static API = {
    /**
     * @method kickstartFactory
     * Generates a kickstart configuration string based on provided options. This kickstart is tailored
     * for use in an Anaconda installer environment with inst.sshd enabled, allowing for SSH access during the installation process.
     * @param {object} options - Options for generating the kickstart file.
     * @param {string} [options.lang='en_US.UTF-8'] - System language.
     * @param {string} [options.keyboard='us'] - Keyboard layout.
     * @param {string} [options.timezone='America/New_York'] - System timezone.
     * @param {string} [options.rootPassword] - Plaintext root password. If not provided, root is locked.
     * @param {string} [options.authorizedKeys] - Public SSH key for root/admin access.
     * @memberof UnderpostKickStart
     * @returns {string} The Kickstart configuration content.
     */
    kickstartFactory: ({
      lang = 'en_US.UTF-8',
      keyboard = 'us',
      timezone = 'America/New_York',
      rootPassword = process.env.MAAS_ADMIN_PASS,
      authorizedKeys = '',
    }) => {
      const adminUsername = process.env.MAAS_ADMIN_USERNAME || 'maas';

      // Sanitize authorized keys - trim and ensure single line per key
      const sanitizedKeys = (authorizedKeys || '').trim();

      return `# Rocky Linux 9 Kickstart - Ephemeral Anaconda Live Environment with SSHD
# Generated by Underpost Engine
#
# This kickstart is designed to run in the Anaconda installer environment
# with inst.sshd on the kernel command line. The %pre script configures
# SSH authentication and then loops forever to keep the live env active.

# Use cmdline mode (non-interactive, no GUI)
cmdline

# Agree to EULA
eula --agreed

# Keyboard layouts
keyboard --vckeymap=${keyboard} --xlayouts='${keyboard}'

# System language
lang ${lang}

# Network - use DHCP on first available link (kernel ip= param takes precedence)
network --bootproto=dhcp --device=link --activate --onboot=yes

# System timezone
timezone ${timezone} --utc

# Root password - plaintext so Anaconda and chpasswd can both use it
${rootPassword ? `rootpw --plaintext ${rootPassword}` : 'rootpw --lock'}

# Do not install to disk - this is an ephemeral environment
firstboot --disable
skipx

# No bootloader, partitioning, or package installation needed for ephemeral mode
# (These are intentionally omitted - we never proceed past %pre)

%pre --interpreter=/bin/bash --log=/tmp/ks-pre.log --erroronfail
#!/bin/bash
# ============================================================================
# Underpost Ephemeral Commissioning - Anaconda %pre Setup
# ============================================================================
# This script runs inside the Anaconda installer environment (initrd-based).
# inst.sshd has already started sshd, but we need to configure authentication.
# After setup, we loop forever to keep the system in the live Anaconda state.
# ============================================================================

set +e  # Don't exit on errors - we want maximum resilience

echo "=============================================="
echo "Underpost: Ephemeral commissioning starting..."
echo "=============================================="
echo "Date: $(date)"
echo "Hostname: $(hostname)"

# ----------------------------------------------------------------------------
# 1. Set root password (works in Anaconda initrd)
# ----------------------------------------------------------------------------
ROOT_PASS='${rootPassword || ''}'
if [ -n "$ROOT_PASS" ]; then
  echo "Setting root password..."
  echo "root:$ROOT_PASS" | chpasswd 2>/dev/null || \\
    echo "$ROOT_PASS" | passwd --stdin root 2>/dev/null || {
      # Last resort: direct shadow manipulation
      HASH=$(python3 -c "import crypt; print(crypt.crypt('$ROOT_PASS', crypt.mksalt(crypt.METHOD_SHA512)))" 2>/dev/null || \\
             openssl passwd -6 "$ROOT_PASS" 2>/dev/null)
      if [ -n "$HASH" ]; then
        sed -i "s|^root:[^:]*:|root:$HASH:|" /etc/shadow 2>/dev/null
        echo "Root password set via shadow file."
      else
        echo "WARNING: Could not set root password by any method."
      fi
    }
  echo "Root password configured."
else
  echo "WARNING: No root password provided. Root login may be locked."
fi

# ----------------------------------------------------------------------------
# 2. Set up SSH authorized_keys for root
# ----------------------------------------------------------------------------
AUTHORIZED_KEYS='${sanitizedKeys}'
if [ -n "$AUTHORIZED_KEYS" ]; then
  echo "Configuring SSH keys for root..."
  mkdir -p /root/.ssh
  chmod 700 /root/.ssh
  echo "$AUTHORIZED_KEYS" > /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
  echo "Root SSH keys configured."
else
  echo "WARNING: No SSH authorized_keys provided."
fi

# ----------------------------------------------------------------------------
# 3. Create admin user (if useradd is available in the Anaconda env)
# ----------------------------------------------------------------------------
ADMIN_USER='${adminUsername}'
echo "Creating admin user: $ADMIN_USER"

# Try useradd first (may exist in Anaconda env)
if command -v useradd >/dev/null 2>&1; then
  useradd -m -G wheel "$ADMIN_USER" 2>/dev/null || {
    # User might already exist
    echo "useradd failed or user exists, trying adduser..."
    adduser "$ADMIN_USER" 2>/dev/null || true
  }
else
  # Manual user creation for minimal initrd environments
  echo "useradd not available, creating user manually..."
  # Determine next available UID
  NEXT_UID=$(awk -F: 'BEGIN{max=999} $3>max && $3<60000{max=$3} END{print max+1}' /etc/passwd 2>/dev/null || echo 1001)
  if ! grep -q "^$ADMIN_USER:" /etc/passwd 2>/dev/null; then
    echo "$ADMIN_USER:x:$NEXT_UID:$NEXT_UID:$ADMIN_USER:/home/$ADMIN_USER:/bin/bash" >> /etc/passwd
    echo "$ADMIN_USER:x:$NEXT_UID:" >> /etc/group 2>/dev/null
    echo "$ADMIN_USER:!:19000:0:99999:7:::" >> /etc/shadow 2>/dev/null
    mkdir -p /home/$ADMIN_USER
  fi
fi

# Set admin password
if [ -n "$ROOT_PASS" ]; then
  echo "$ADMIN_USER:$ROOT_PASS" | chpasswd 2>/dev/null || \\
    echo "$ROOT_PASS" | passwd --stdin "$ADMIN_USER" 2>/dev/null || {
      HASH=$(python3 -c "import crypt; print(crypt.crypt('$ROOT_PASS', crypt.mksalt(crypt.METHOD_SHA512)))" 2>/dev/null || \\
             openssl passwd -6 "$ROOT_PASS" 2>/dev/null)
      if [ -n "$HASH" ]; then
        sed -i "s|^$ADMIN_USER:[^:]*:|$ADMIN_USER:$HASH:|" /etc/shadow 2>/dev/null
      fi
    }
  echo "Admin user password set."
fi

# Set up SSH keys for admin user
if [ -n "$AUTHORIZED_KEYS" ]; then
  mkdir -p /home/$ADMIN_USER/.ssh
  chmod 700 /home/$ADMIN_USER/.ssh
  echo "$AUTHORIZED_KEYS" > /home/$ADMIN_USER/.ssh/authorized_keys
  chmod 600 /home/$ADMIN_USER/.ssh/authorized_keys
  chown -R $ADMIN_USER:$ADMIN_USER /home/$ADMIN_USER/.ssh 2>/dev/null || true
  echo "Admin SSH keys configured."
fi

# Set up passwordless sudo for admin user
if [ -d /etc/sudoers.d ]; then
  echo "$ADMIN_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$ADMIN_USER
  chmod 0440 /etc/sudoers.d/$ADMIN_USER
  echo "Sudo configured for $ADMIN_USER."
elif [ -f /etc/sudoers ]; then
  echo "$ADMIN_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
fi

# ----------------------------------------------------------------------------
# 4. Configure sshd for both password and pubkey auth
# ----------------------------------------------------------------------------
echo "Configuring sshd..."

# If sshd_config exists, patch it; otherwise create a minimal one
if [ -f /etc/ssh/sshd_config ]; then
  # Enable password authentication
  sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  sed -i 's/^#*PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
  sed -i 's/^#*ChallengeResponseAuthentication.*/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
  sed -i 's/^#*UsePAM.*/UsePAM yes/' /etc/ssh/sshd_config
  sed -i 's/^#*KbdInteractiveAuthentication.*/KbdInteractiveAuthentication yes/' /etc/ssh/sshd_config

  # Ensure settings exist if not already present
  grep -q "^PasswordAuthentication" /etc/ssh/sshd_config || echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
  grep -q "^PermitRootLogin" /etc/ssh/sshd_config || echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  grep -q "^PubkeyAuthentication" /etc/ssh/sshd_config || echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
else
  # Create minimal sshd config
  mkdir -p /etc/ssh
  cat > /etc/ssh/sshd_config << 'SSHEOF'
Port 22
PermitRootLogin yes
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication yes
ChallengeResponseAuthentication yes
KbdInteractiveAuthentication yes
UsePAM yes
Subsystem sftp /usr/libexec/openssh/sftp-server
SSHEOF
fi

# Also drop a config snippet if sshd_config.d exists
if [ -d /etc/ssh/sshd_config.d ]; then
  cat > /etc/ssh/sshd_config.d/00-underpost.conf << 'SSHCONF'
PermitRootLogin yes
PasswordAuthentication yes
PubkeyAuthentication yes
KbdInteractiveAuthentication yes
SSHCONF
fi

# Generate host keys if missing (Anaconda env might not have them)
if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
  ssh-keygen -A 2>/dev/null || {
    ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N "" 2>/dev/null
    ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N "" 2>/dev/null
    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" 2>/dev/null
  }
fi

# ----------------------------------------------------------------------------
# 5. Initialize rpmdb, release identity, and configure dnf repos
# ----------------------------------------------------------------------------
# The Anaconda initrd has no writable rpmdb and may lack proper os-release /
# releasever — we must create everything from scratch so that dnf/rpm can
# function over SSH in this ephemeral environment.
echo "Initializing rpmdb, release identity, and dnf repositories..."

# Ensure writable directories exist
mkdir -p /var/lib/rpm
mkdir -p /var/cache/dnf
mkdir -p /var/log/dnf
mkdir -p /etc/yum.repos.d
mkdir -p /etc/pki/rpm-gpg
mkdir -p /etc/dnf/vars

# --- Set release version so dnf can resolve $releasever ---
echo "9" > /etc/dnf/vars/releasever
echo "Rocky Linux 9 releasever set."

# --- Write /etc/os-release if missing or incomplete ---
if ! grep -q "^VERSION_ID=" /etc/os-release 2>/dev/null; then
  cat > /etc/os-release << 'OSREL'
NAME="Rocky Linux"
VERSION="9"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9 (Ephemeral Anaconda)"
ANSI_COLOR="0;32"
HOME_URL="https://rockylinux.org/"
OSREL
  echo "/etc/os-release written."
fi

# --- Write /etc/system-release for rpm macros ---
if [ ! -f /etc/system-release ]; then
  echo "Rocky Linux release 9 (Ephemeral)" > /etc/system-release
fi

# Initialize the RPM database
rpm --initdb 2>/dev/null || rpmdb --initdb 2>/dev/null || {
  echo "WARNING: Could not initialize rpmdb with rpm/rpmdb commands."
  # Last resort: create empty sqlite db manually
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "
import sqlite3, os
db_path = '/var/lib/rpm/rpmdb.sqlite'
if not os.path.exists(db_path):
    conn = sqlite3.connect(db_path)
    conn.execute('CREATE TABLE IF NOT EXISTS Packages (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Name (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Basenames (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Installtid (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Providename (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Requirename (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Dirnames (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Sha1header (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.execute('CREATE TABLE IF NOT EXISTS Sigmd5 (key BLOB NOT NULL, data BLOB NOT NULL)')
    conn.commit()
    conn.close()
    print('Created empty rpmdb.sqlite')
" 2>/dev/null
  fi
}
chmod -R 755 /var/lib/rpm 2>/dev/null

# Detect architecture for repo URLs
REPO_ARCH=$(uname -m)

# Import Rocky Linux 9 GPG keys (try multiple sources)
rpm --import https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9 2>/dev/null || \\
  curl -fsSL https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9 -o /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9 2>/dev/null || true

# Write dnf.conf for the ephemeral environment
cat > /etc/dnf/dnf.conf << 'DNFCONF'
[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=True
best=True
skip_if_unavailable=True
install_weak_deps=False
tsflags=nodocs
DNFCONF

# Write BaseOS repo
cat > /etc/yum.repos.d/rocky-baseos.repo << REPOEOF
[baseos]
name=Rocky Linux 9 - BaseOS
baseurl=http://dl.rockylinux.org/pub/rocky/9/BaseOS/$REPO_ARCH/os/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
       https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9
skip_if_unavailable=1
REPOEOF

# Write AppStream repo
cat > /etc/yum.repos.d/rocky-appstream.repo << REPOEOF2
[appstream]
name=Rocky Linux 9 - AppStream
baseurl=http://dl.rockylinux.org/pub/rocky/9/AppStream/$REPO_ARCH/os/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
       https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9
skip_if_unavailable=1
REPOEOF2

# Write Extras repo
cat > /etc/yum.repos.d/rocky-extras.repo << REPOEOF3
[extras]
name=Rocky Linux 9 - Extras
baseurl=http://dl.rockylinux.org/pub/rocky/9/extras/$REPO_ARCH/os/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
       https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9
skip_if_unavailable=1
REPOEOF3

# Write CRB (CodeReady Builder / PowerTools) repo
cat > /etc/yum.repos.d/rocky-crb.repo << REPOEOF4
[crb]
name=Rocky Linux 9 - CRB
baseurl=http://dl.rockylinux.org/pub/rocky/9/CRB/$REPO_ARCH/os/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
       https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9
skip_if_unavailable=1
REPOEOF4

# Write EPEL repo for extra packages (like fastfetch)
cat > /etc/yum.repos.d/epel.repo << REPOEOF5
[epel]
name=Extra Packages for Enterprise Linux 9
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-9&arch=$REPO_ARCH
gpgcheck=1
enabled=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
skip_if_unavailable=1
REPOEOF5

# Import EPEL GPG key
rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9 2>/dev/null || \\
  curl -fsSL https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9 -o /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9 2>/dev/null || true

# Build dnf metadata cache (foreground — needed before we can install sudo)
echo "Building dnf metadata cache (this may take a moment)..."
dnf makecache --releasever=9 --quiet 2>/dev/null || dnf makecache --releasever=9 2>/dev/null || {
  echo "WARNING: dnf makecache failed — package installs may still work on first use."
}

echo "rpmdb and dnf repos configured (BaseOS, AppStream, Extras, CRB, EPEL)."

# ----------------------------------------------------------------------------
# 5b. Bootstrap essential packages: sudo
# ----------------------------------------------------------------------------
# The Anaconda initrd does not ship sudo — install it now so the admin user
# can escalate privileges over SSH.
echo "Installing sudo via dnf..."
if ! command -v sudo >/dev/null 2>&1; then
  dnf install -y --releasever=9 --nogpgcheck sudo 2>/dev/null && {
    echo "sudo installed successfully."
  } || {
    echo "WARNING: dnf install sudo failed. Trying alternative methods..."
    # Try with --disableplugin to avoid plugin issues in minimal env
    dnf install -y --releasever=9 --nogpgcheck --disableplugin='*' sudo 2>/dev/null || {
      echo "WARNING: Could not install sudo. Use 'su -' to switch to root."
    }
  }
else
  echo "sudo already available."
fi

# Re-apply sudoers config for admin user (in case sudo was just installed
# and /etc/sudoers.d was recreated by the package)
if command -v sudo >/dev/null 2>&1; then
  mkdir -p /etc/sudoers.d
  echo "$ADMIN_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$ADMIN_USER
  chmod 0440 /etc/sudoers.d/$ADMIN_USER
  echo "Sudoers refreshed for $ADMIN_USER."
fi

# Provide 'su -' as fallback privilege escalation — create a helper hint
# so the admin user knows how to get root if sudo is missing
cat > /home/$ADMIN_USER/.bash_profile 2>/dev/null << PROFILEEOF
# Underpost Ephemeral Commissioning Environment
if ! command -v sudo >/dev/null 2>&1; then
  echo ""
  echo "NOTE: sudo is not available. Use 'su -' to switch to root."
  echo "      Root password is the same as your login password."
  echo ""
fi
PROFILEEOF
chown $ADMIN_USER:$ADMIN_USER /home/$ADMIN_USER/.bash_profile 2>/dev/null || true

# Restart sshd to apply configuration changes
echo "Restarting sshd to apply auth changes..."
# Try systemctl first, then direct kill/restart
if command -v systemctl >/dev/null 2>&1; then
  systemctl restart sshd 2>/dev/null || systemctl restart sshd.service 2>/dev/null
fi
# Also try direct process restart as fallback
SSHD_PID=$(cat /var/run/sshd.pid 2>/dev/null || pidof sshd 2>/dev/null | awk '{print $1}')
if [ -n "$SSHD_PID" ]; then
  kill -HUP "$SSHD_PID" 2>/dev/null
  echo "Sent SIGHUP to sshd (pid $SSHD_PID)."
fi
# If sshd is not running at all, start it
if ! pidof sshd >/dev/null 2>&1; then
  /usr/sbin/sshd 2>/dev/null || sshd 2>/dev/null
  echo "Started sshd manually."
fi

# ----------------------------------------------------------------------------
# 6. Verify setup and report status
# ----------------------------------------------------------------------------
echo ""
echo "=============================================="
echo "Underpost: Ephemeral SSHD Setup Complete"
echo "=============================================="
echo "Root login:  root / (password set: $([ -n "$ROOT_PASS" ] && echo 'yes' || echo 'no'))"
echo "Admin user:  $ADMIN_USER / (password set: $([ -n "$ROOT_PASS" ] && echo 'yes' || echo 'no'))"
echo "SSH keys:    $([ -n "$AUTHORIZED_KEYS" ] && echo 'configured' || echo 'NOT configured')"
echo "sshd status: $(pidof sshd >/dev/null 2>&1 && echo "running (pid $(pidof sshd))" || echo 'NOT running')"
echo "sudo:        $(command -v sudo >/dev/null 2>&1 && echo 'installed' || echo 'NOT available (use su -)')"
echo "dnf/rpm:     $(rpm -q rpm >/dev/null 2>&1 && echo 'rpmdb ok' || echo 'rpmdb initialized (empty)') / $(ls /etc/yum.repos.d/*.repo 2>/dev/null | wc -l) repos configured"
echo "releasever:  $(cat /etc/dnf/vars/releasever 2>/dev/null || echo 'NOT SET')"
DETECTED_IP=$(ip -4 addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | cut -d/ -f1 | head -1)
echo "IP address:  $DETECTED_IP"
echo "=============================================="
echo ""

# Send summary to console for physical display
{
  echo ""
  echo "=============================================="
  echo " Underpost Ephemeral Commissioning Active"
  echo "=============================================="
  echo " SSH as: root@$DETECTED_IP"
  echo "     or: $ADMIN_USER@$DETECTED_IP"
  echo " Key:    $([ -n "$AUTHORIZED_KEYS" ] && echo 'pubkey auth enabled' || echo 'password only')"
  echo " dnf:    ready (BaseOS, AppStream, Extras, EPEL)"
  echo "=============================================="
  echo ""
} > /dev/console 2>/dev/null || true

# ----------------------------------------------------------------------------
# 7. Loop forever to keep the Anaconda live environment active
# ----------------------------------------------------------------------------
# This prevents the installer from proceeding past %pre, keeping the
# ephemeral environment with sshd running indefinitely for commissioning.
echo "Entering infinite wait loop - system will stay in live Anaconda mode."
echo "Use the SSH connection to perform commissioning tasks."

while true; do
  sleep 60
  # Periodic health check - restart sshd if it died
  if ! pidof sshd >/dev/null 2>&1; then
    echo "$(date): sshd not running, restarting..." >> /tmp/ks-pre.log
    /usr/sbin/sshd 2>/dev/null || sshd 2>/dev/null
  fi
done
%end
`;
    },
  };
}

export default UnderpostKickStart;
