apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb # Specifies the name of the statefulset
spec:
  serviceName: 'mongodb-service' # Specifies the service to use
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: docker.io/library/mongo:latest
          command:
            - mongod
            - '--replSet'
            - 'rs0'
            # - '--config'
            # - '-f'
            # - '/etc/mongod.conf'
            # - '--auth'
            # - '--clusterAuthMode'
            # - 'keyFile'
            # - '--keyFile'
            # - '/etc/mongodb-keyfile'
            # - '--interleave'
            # - 'all'
            # - '--wiredTigerCacheSizeGB'
            # - '0.25'
            # - '--setParameter'
            # - 'authenticationMechanisms=SCRAM-SHA-1'
            # - '--fork'
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
            - '--bind_ip_all'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
            - name: keyfile
              mountPath: /etc/mongodb-keyfile
              readOnly: true
            # - name: mongodb-configuration-file
            #   mountPath: /etc/mongod.conf
            #   subPath: mongod.conf
            #   readOnly: true
            # - name: mongodb-config
            #   mountPath: /config
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
      volumes:
        - name: keyfile
          secret:
            secretName: mongodb-keyfile
            defaultMode: 0400
        # - name: mongodb-configuration-file
        #   configMap:
        #     name: mongodb-config-file
        # - name: mongodb-config
        #   configMap:
        #     name: mongodb-config
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 5Gi
