apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: '*/5 * * * *' # Runs backup every five minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongodump
              image: mongo:latest
              command:
                - sh
                - -c
                - |
                  # Perform backup
                  mongodump --host=mongodb-service --port=27017 --out=/backup/$(date +\%Y-\%m-\%dT\%H-\%M-\%S)
                  # Remove backups older than 7 days
                  find /backup -type d -mtime +7 -exec rm -rf {} +
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: Never
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc
