---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-test-development-blue
  namespace: default
  labels:
    app: dd-test-development-blue
    deploy-id: dd-test-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-test-development-blue
  template:
    metadata:
      labels:
        app: dd-test-development-blue
        deploy-id: dd-test-development
    spec:
      containers:
        - name: dd-test-development-blue
          image: localhost/rockylinux9-underpost:v3.2.5
          envFrom:
            - secretRef:
                name: underpost-config

          command:
            - /bin/sh
            - -c
            - >
              npm install -g npm@11.2.0 &&
              npm install -g underpost &&
              underpost secret underpost --create-from-env &&
              underpost start --build --run dd-test development


---
apiVersion: v1
kind: Service
metadata:
  name: dd-test-development-blue-service
  namespace: default
spec:
  selector:
    app: dd-test-development-blue
  ports:
    - name: 'tcp-4049'
      protocol: TCP
      port: 4049
      targetPort: 4049
    - name: 'udp-4049'
      protocol: UDP
      port: 4049
      targetPort: 4049

    - name: 'tcp-4050'
      protocol: TCP
      port: 4050
      targetPort: 4050
    - name: 'udp-4050'
      protocol: UDP
      port: 4050
      targetPort: 4050

    - name: 'tcp-4051'
      protocol: TCP
      port: 4051
      targetPort: 4051
    - name: 'udp-4051'
      protocol: UDP
      port: 4051
      targetPort: 4051

    - name: 'tcp-4052'
      protocol: TCP
      port: 4052
      targetPort: 4052
    - name: 'udp-4052'
      protocol: UDP
      port: 4052
      targetPort: 4052

    - name: 'tcp-4053'
      protocol: TCP
      port: 4053
      targetPort: 4053
    - name: 'udp-4053'
      protocol: UDP
      port: 4053
      targetPort: 4053
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-test-development-green
  namespace: default
  labels:
    app: dd-test-development-green
    deploy-id: dd-test-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-test-development-green
  template:
    metadata:
      labels:
        app: dd-test-development-green
        deploy-id: dd-test-development
    spec:
      containers:
        - name: dd-test-development-green
          image: localhost/rockylinux9-underpost:v3.2.5
          envFrom:
            - secretRef:
                name: underpost-config

          command:
            - /bin/sh
            - -c
            - >
              npm install -g npm@11.2.0 &&
              npm install -g underpost &&
              underpost secret underpost --create-from-env &&
              underpost start --build --run dd-test development


---
apiVersion: v1
kind: Service
metadata:
  name: dd-test-development-green-service
  namespace: default
spec:
  selector:
    app: dd-test-development-green
  ports:
    - name: 'tcp-4049'
      protocol: TCP
      port: 4049
      targetPort: 4049
    - name: 'udp-4049'
      protocol: UDP
      port: 4049
      targetPort: 4049

    - name: 'tcp-4050'
      protocol: TCP
      port: 4050
      targetPort: 4050
    - name: 'udp-4050'
      protocol: UDP
      port: 4050
      targetPort: 4050

    - name: 'tcp-4051'
      protocol: TCP
      port: 4051
      targetPort: 4051
    - name: 'udp-4051'
      protocol: UDP
      port: 4051
      targetPort: 4051

    - name: 'tcp-4052'
      protocol: TCP
      port: 4052
      targetPort: 4052
    - name: 'udp-4052'
      protocol: UDP
      port: 4052
      targetPort: 4052

    - name: 'tcp-4053'
      protocol: TCP
      port: 4053
      targetPort: 4053
    - name: 'udp-4053'
      protocol: UDP
      port: 4053
      targetPort: 4053
  type: LoadBalancer
