---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-test-development-blue
  namespace: default
  labels:
    app: dd-test-development-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-test-development-blue
  template:
    metadata:
      labels:
        app: dd-test-development-blue
    spec:
      containers:
        - name: dd-test-development-blue
          image: localhost/rockylinux9-underpost:v3.1.3

          command:
            - /bin/sh
            - -c
            - >
              npm install -g npm@11.2.0 && npm install -g underpost && underpost secret underpost --create-from-file /etc/config/.env.development && underpost start --build --run dd-test development

    
          volumeMounts:
            - name: config-volume-dd-test-development-blue
              mountPath: /etc/config
    
      volumes:
        - name: config-volume-dd-test-development-blue
          configMap:
            name: underpost-config
    
      
---
apiVersion: v1
kind: Service
metadata:
  name: dd-test-development-blue-service
  namespace: default
spec:
  selector:
    app: dd-test-development-blue
  ports:
    - name: 'tcp-4046'
      protocol: TCP
      port: 4046
      targetPort: 4046
    - name: 'udp-4046'
      protocol: UDP
      port: 4046
      targetPort: 4046

    - name: 'tcp-4047'
      protocol: TCP
      port: 4047
      targetPort: 4047
    - name: 'udp-4047'
      protocol: UDP
      port: 4047
      targetPort: 4047

    - name: 'tcp-4048'
      protocol: TCP
      port: 4048
      targetPort: 4048
    - name: 'udp-4048'
      protocol: UDP
      port: 4048
      targetPort: 4048

    - name: 'tcp-4049'
      protocol: TCP
      port: 4049
      targetPort: 4049
    - name: 'udp-4049'
      protocol: UDP
      port: 4049
      targetPort: 4049
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-test-development-green
  namespace: default
  labels:
    app: dd-test-development-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-test-development-green
  template:
    metadata:
      labels:
        app: dd-test-development-green
    spec:
      containers:
        - name: dd-test-development-green
          image: localhost/rockylinux9-underpost:v3.1.3

          command:
            - /bin/sh
            - -c
            - >
              npm install -g npm@11.2.0 && npm install -g underpost && underpost secret underpost --create-from-file /etc/config/.env.development && underpost start --build --run dd-test development

    
          volumeMounts:
            - name: config-volume-dd-test-development-green
              mountPath: /etc/config
    
      volumes:
        - name: config-volume-dd-test-development-green
          configMap:
            name: underpost-config
    
      
---
apiVersion: v1
kind: Service
metadata:
  name: dd-test-development-green-service
  namespace: default
spec:
  selector:
    app: dd-test-development-green
  ports:
    - name: 'tcp-4046'
      protocol: TCP
      port: 4046
      targetPort: 4046
    - name: 'udp-4046'
      protocol: UDP
      port: 4046
      targetPort: 4046

    - name: 'tcp-4047'
      protocol: TCP
      port: 4047
      targetPort: 4047
    - name: 'udp-4047'
      protocol: UDP
      port: 4047
      targetPort: 4047

    - name: 'tcp-4048'
      protocol: TCP
      port: 4048
      targetPort: 4048
    - name: 'udp-4048'
      protocol: UDP
      port: 4048
      targetPort: 4048

    - name: 'tcp-4049'
      protocol: TCP
      port: 4049
      targetPort: 4049
    - name: 'udp-4049'
      protocol: UDP
      port: 4049
      targetPort: 4049
  type: LoadBalancer
