
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test.nexodev.org
  namespace: default
spec:
  virtualhost:
    fqdn: test.nexodev.org
  routes:
    - conditions:
        - prefix: /wp
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4033
          weight: 100
    
    - conditions:
        - prefix: /
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4034
          weight: 100
    
    - conditions:
        - prefix: /peer
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4035
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: stagging.nexodev.org
  namespace: default
spec:
  virtualhost:
    fqdn: stagging.nexodev.org
  routes:
    - conditions:
        - prefix: /
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4036
          weight: 100
    
    - conditions:
        - prefix: /peer
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4037
          weight: 100
    