
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: test.nexodev.org
  namespace: default
spec:
  virtualhost:
    fqdn: test.nexodev.org
  routes:
    - conditions:
        - prefix: /wp
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4049
          weight: 100
    
    - conditions:
        - prefix: /
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4050
          weight: 100
    
    - conditions:
        - prefix: /peer
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4051
          weight: 100
    
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: stagging.nexodev.org
  namespace: default
spec:
  virtualhost:
    fqdn: stagging.nexodev.org
  routes:
    - conditions:
        - prefix: /
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4052
          weight: 100
    
    - conditions:
        - prefix: /peer
      
      enableWebsockets: true
      services:
        - name: dd-test-development-blue-service
          port: 4053
          weight: 100
    