import { describe, it, expect } from 'vitest';
import NginxService from '../../../src/runtime/nginx/Nginx.js';

const blockOf = (conf, head) => conf.slice(conf.indexOf(head), conf.indexOf('\n}', conf.indexOf(head)) + 2);

describe('nginx primitives', () => {
  it('proxies a host target directly when no resolver is set', () => {
    const conf = new NginxService()
      .addServer({ names: ['app.test'], locations: [{ match: '/', proxy: 'app:4001' }] })
      .render();
    expect(conf).toContain('proxy_pass http://app:4001;');
    expect(conf).not.toContain('resolver');
    expect(conf).toContain('proxy_set_header Connection $connection_upgrade;');
  });

  it('resolves a host target per request through the resolver', () => {
    const conf = new NginxService()
      .useResolver()
      .addServer({ locations: [{ match: '/', proxy: 'cyberia-client-test:8081' }] })
      .render();
    expect(conf).toContain('resolver 127.0.0.11 ipv6=off valid=10s;');
    expect(conf).toContain('set $up_cyberia_client_test_8081 cyberia-client-test:8081;');
    expect(conf).toContain('proxy_pass http://$up_cyberia_client_test_8081;');
  });

  it('proxies a map variable as it is', () => {
    const conf = new NginxService()
      .useResolver()
      .addMap({ source: '$host', variable: '$engine', entries: { default: 'engine:1', 'a.test': 'engine:2' } })
      .addServer({ names: ['a.test'], locations: [{ match: '/', proxy: '$engine' }] })
      .render();
    expect(blockOf(conf, 'map $host $engine')).toMatch(/default\s+engine:1;\n\s+a\.test\s+engine:2;/);
    expect(conf).toContain('proxy_pass http://$engine;');
  });

  it('renders listens, names, the health probe and redirects', () => {
    const conf = new NginxService()
      .addServer({
        listen: [80, '8081 default_server'],
        names: ['server.test', 'alias.test'],
        health: true,
        locations: [{ match: '= /test', redirect: '/test/' }],
      })
      .render();
    const server = blockOf(conf, 'server {');
    expect(server).toContain(
      '    listen 80;\n    listen 8081 default_server;\n    server_name server.test alias.test;',
    );
    expect(server).toContain('location = /healthz {');
    expect(server).toContain('return 200 "ok\\n";');
    expect(server).toContain('location = /test {\n        return 301 /test/;\n    }');
  });

  it('names its origin and starts over after a reset', () => {
    const nginx = new NginxService().useResolver().addServer({ locations: [{ match: '/', proxy: 'a:1' }] });
    expect(nginx.render({ origin: "'gen'" }).split('\n')[0]).toBe("# Generated by 'gen' — do not hand-edit.");
    const conf = nginx.reset().render();
    expect(conf).not.toContain('server {');
    expect(conf).not.toContain('resolver');
    expect(conf).toContain('map $http_upgrade $connection_upgrade');
  });
});
