apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb # Specifies the name of the statefulset
spec:
  serviceName: 'mongodb-service' # Specifies the service to use
  podManagementPolicy: OrderedReady # or Parallel
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      subdomain: mongodb-service
      securityContext:
        fsGroup: 999
      initContainers:
        - name: internal-keyfile-provisioner
          image: docker.io/library/mongo:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - |
              set -ex
              mkdir -p /opt/mongodb
              cp /tmp/raw-keyfile/mongodb-keyfile /opt/mongodb/mongodb-keyfile
              chmod 400 /opt/mongodb/mongodb-keyfile
              chown -R 999:999 /opt/mongodb
              chown -R 999:999 /data/db
              rm -f /data/db/mongod.lock
          volumeMounts:
            - name: raw-secret-keyfile-volume
              mountPath: /tmp/raw-keyfile
            - name: isolated-runtime-keyfile-volume
              mountPath: /opt/mongodb
            - name: mongodb-storage
              mountPath: /data/db
      containers:
        - name: mongodb
          image: docker.io/library/mongo:latest
          command:
            - mongod
          args:
            - '--replSet'
            - 'rs0'
            - '--auth'
            - '--clusterAuthMode'
            - 'keyFile'
            - '--keyFile'
            - '/opt/mongodb/mongodb-keyfile'
            - '--bind_ip_all'
          # command: ['sh', '-c']
          # args:
          #   - |
          #     mongod --replSet rs0 --bind_ip_all &
          #     sleep 1000
          #     if mongosh --host mongodb-0.mongodb-service:27017 --eval "rs.status()" | grep -q "not yet initialized"; then
          #       mongosh --host mongodb-0.mongodb-service:27017 <<EOF
          #       use admin;
          #       rs.initiate({
          #         _id: "rs0",
          #         members: [
          #           { _id: 0, host: "mongodb-0.mongodb-service:27017", priority: 1 },
          #           { _id: 1, host: "mongodb-1.mongodb-service:27017", priority: 1 }
          #         ]
          #       });
          #       db.getSiblingDB("admin").createUser({
          #         user: process.env.MONGO_INITDB_ROOT_USERNAME,
          #         pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
          #         roles: [{ role: "userAdminAnyDatabase", db: "admin" }]
          #       });
          #       use default;
          #       db.createUser(
          #         {
          #           user: process.env.MONGO_INITDB_ROOT_USERNAME,
          #           pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
          #           roles: [
          #             { role: "read", db: "test" },
          #             { role: "readWrite", db: "default" }
          #           ]
          #         }
          #       );
          #       EOF
          #     fi
          #     wait
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: isolated-runtime-keyfile-volume
              mountPath: /opt/mongodb
            - name: mongodb-storage
              mountPath: /data/db
            # - name: mongodb-configuration-file
            #   mountPath: /etc/mongod.conf
            #   subPath: mongod.conf
            #   readOnly: true
            # - name: mongodb-config
            #   mountPath: /config
          env:
            - name: MONGO_REPLICA_SET_NAME
              value: rs0
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
      volumes:
        - name: raw-secret-keyfile-volume
          secret:
            secretName: mongodb-keyfile
            defaultMode: 0400
        - name: isolated-runtime-keyfile-volume
          emptyDir: {}
        # - name: mongodb-configuration-file
        #   configMap:
        #     name: mongodb-config-file
        # - name: mongodb-config
        #   configMap:
        #     name: mongodb-config
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: mongodb-storage-class
        resources:
          requests:
            storage: 5Gi
