---
apiVersion: v1
kind: Service
metadata:
  name: service-valkey
  namespace: default
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: service-valkey
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    # - IPv6
  type: ClusterIP
