apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-valkey
  namespace: default
spec:
  serviceName: service-valkey
  replicas: 1
  selector:
    matchLabels:
      app: service-valkey
  template:
    metadata:
      labels:
        app: service-valkey
    spec:
      # Prevent automatic token mounting if you're not using the default ServiceAccount
      automountServiceAccountToken: false

      containers:
        - name: service-valkey
          image: valkey/valkey:latest
          # Ensure you pull only if not present (Never will error if missing)
          imagePullPolicy: Never
          env:
            - name: TZ
              value: Europe/Zurich
          ports:
            - containerPort: 6379
          startupProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
