import { SocketIo } from './components/core/SocketIo.js';
import { Responsive } from './components/core/Responsive.js';
import { Keyboard } from './components/core/Keyboard.js';
import { append, disableOptionsClick, s } from './components/core/VanillaJs.js';
import { NotificationManager } from './components/core/NotificationManager.js';
import { Pixi } from './components/cyberia/Pixi.js';
import { Elements } from './components/cyberia/Elements.js';
import { TranslateCyberia } from './components/cyberia/TranslateCyberia.js';
import { JoyStick } from './components/cyberia/JoyStick.js';
import { MainUser } from './components/cyberia/MainUser.js';
import { LoadingAnimation } from './components/core/LoadingAnimation.js';
import { SocketIoCyberia } from './components/cyberia/SocketIoCyberia.js';
import { LogOutCyberia } from './components/cyberia/LogOutCyberia.js';
import { LogInCyberia } from './components/cyberia/LogInCyberia.js';
import { TranslateCore } from './components/core/Translate.js';
import { Menu } from './components/cyberia/Menu.js';
import { LoadRouter } from './components/core/Router.js';
import { RouterCyberia } from './components/cyberia/RoutesCyberia.js';

await LoadingAnimation.bar.play('init-loading');
window.eventCallbackTime = 45;
const RouterInstance = RouterCyberia();
await TranslateCore.Init();
await TranslateCyberia.Init();
append('body', await MainUser.Render());
await Pixi.Init();
await Responsive.Init();
await Keyboard.Init();
append('body', await JoyStick.Render());
await Menu.Render();
await NotificationManager.RenderBoard();
disableOptionsClick('html', ['drag', 'select']);
await SocketIo.Init({ channels: Elements.Data });
await SocketIoCyberia.Init();
await LogOutCyberia();
await LogInCyberia();
LoadRouter(RouterInstance);
s(`.btn-menu-modal-menu`).click();
