'use strict';

import { SocketIo } from './components/core/SocketIo.js';
import { Responsive } from './components/core/Responsive.js';
import { Keyboard } from './components/core/Keyboard.js';
import { disableOptionsClick, s } from './components/core/VanillaJs.js';
import { NotificationManager } from './components/core/NotificationManager.js';
import { Pixi } from './components/cyberia/Pixi.js';
import { Elements } from './components/cyberia/Elements.js';
import { TranslateCyberia } from './components/cyberia/TranslateCyberia.js';
import { JoyStickCyberia } from './components/cyberia/JoyStickCyberia.js';
import { MainUser } from './components/cyberia/MainUser.js';
import { LoadingAnimation } from './components/core/LoadingAnimation.js';
import { SocketIoCyberia } from './components/cyberia/SocketIoCyberia.js';
import { LogOutCyberia } from './components/cyberia/LogOutCyberia.js';
import { TranslateCore } from './components/core/Translate.js';
import { Menu } from './components/cyberia/Menu.js';
import { LoadRouter } from './components/core/Router.js';
import { RouterCyberia } from './components/cyberia/RoutesCyberia.js';
import { Css } from './components/core/Css.js';
import { CssCyberia } from './components/cyberia/CssCyberia.js';
import { Skill } from './components/cyberia/Skill.js';
import { PointAndClickMovement } from './components/cyberia/PointAndClickMovement.js';
import { SignUpCyberia } from './components/cyberia/SignUpCyberia.js';

(async function () {
  await Css.Init(CssCyberia);
  await LoadingAnimation.bar.play('init-loading');
  const RouterInstance = RouterCyberia();
  await TranslateCore.Init();
  await TranslateCyberia.Init();
  await MainUser.Render();
  await Pixi.Init();
  await Responsive.Init();
  await Menu.Render();
  await NotificationManager.RenderBoard();
  await PointAndClickMovement.Render();
  await SocketIo.Init({ channels: Elements.Data });
  await SocketIoCyberia.Init();
  await LogOutCyberia();
  await SignUpCyberia();
  LoadRouter(RouterInstance);
  disableOptionsClick('html', ['drag', 'select', 'menu']);
  s(`.btn-menu-modal-menu`).click();
  await Skill.renderMainKeysSlots();
  await Keyboard.Init();
  await JoyStickCyberia.Render();
})();
