name: Test
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  test:
    name: Coverall Test
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          dnf install -y sudo tar gzip bzip2
          dnf install -y curl --allowerasing

      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_23.x | bash -
          dnf install -y nodejs
      - name: Get npm root
        run: sudo npm root -g

      - name: Install underpost cli
        run: sudo npm install -g underpost

      - name: Run test
        run: sudo underpost test

      # for travis
      # - name: Run coveralls
      #   run: npm run coveralls # nyc npm run test --reporter=text-lcov | coveralls -v

      # - name: Test token
      #   run: echo "${{ secrets.COVERALLS_REPO_TOKEN }}"

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     flag-name: ${{matrix.os}}-node-${{ matrix.node }}
      #     parallel: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: '/usr/local/lib/node_modules/underpost/coverage/lcov.info'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    #     COVERALLS_GIT_BRANCH: "${{ github.ref }}"

    # - name: Coveralls
    #   run: node ./node_modules/coveralls-next/bin/coveralls.js # cat ./coverage/lcov.info |
    #   env:
    #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    #     COVERALLS_SERVICE_NAME: CI-pipeline
    #     COVERALLS_SERVICE_JOB_ID: ${{github.run_id}}
    #     COVERALLS_SERVICE_JOB_NUMBER: ${{github.run_number}}
    #     COVERALLS_FLAG_NAME: ${{matrix.os}}-node-${{ matrix.node }}
    #     COVERALLS_PARALLEL: true
    #     NODE_COVERALLS_DEBUG: 1
  finish:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Coveralls Finished
        run: |
          curl -kv -d 'payload[build_num]=${{github.run_id}}&payload[status]=done' https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_GIT_BRANCH: '${{ github.ref }}'
