name: CI | Coverall

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    name: Coverall Test
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          dnf install -y sudo tar gzip bzip2 git
          dnf install -y curl --allowerasing

      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_23.x | bash -
          dnf install nodejs -y

      - name: Install project dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm run test

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Notify Coveralls Finished
        run: |
          curl -s -X POST -d 'payload[build_num]=${{ github.run_id }}&payload[status]=done' \
            "https://coveralls.io/webhook?repo_token=${{ secrets.COVERALLS_REPO_TOKEN }}"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
