name: Engine lampp Repo Builder
on:
  workflow_run:
    workflows: ['Update npm repo package']
    types:
      - completed
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  pwa-microservices-template:
    # if: github.repository == 'underpostnet/engine' && startsWith(github.event.head_commit.message, 'ci(engine-lampp-repo-build)')
    name: Update github repo package Jobs
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install required packages
        run: |
          dnf install -y sudo tar gzip bzip2
          dnf install -y curl --allowerasing

      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_23.x | bash -
          dnf install -y nodejs

      - name: Install dependencies
        run: |
          npm install -g underpost
          npm install
          underpost config set GITHUB_TOKEN ${{ secrets.GIT_AUTH_TOKEN }}

      - name: Set git credentials
        run: |
          git config --global credential.helper ""
          git config credential.helper ""
          git config --global user.name 'underpostnet'
          git config --global user.email 'development@underpost.net'
          git config --global credential.interactive always
          git config user.name 'underpostnet'
          git config user.email 'development@underpost.net'
          git config credential.interactive always

      - name: Build repository
        run: |
          cd .. && underpost clone underpostnet/pwa-microservices-template
          underpost clone --bare underpostnet/engine-lampp
          cd engine
          node bin/build dd-lampp development
          cd ../pwa-microservices-template
          rm -rf ./.git
          mv ../engine-lampp.git ./.git
          git init
          git add .
          underpost cmt . ci engine-lampp-repo-build 'Update engine lampp repository'
          underpost push . underpostnet/engine-lampp
