name: Update github repo package
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  pwa-microservices-template-ghpk:
    if: github.repository == 'underpostnet/pwa-microservices-template' && startsWith(github.event.head_commit.message, 'ci(package-pwa-microservices-template-ghpkg)')
    name: Update github repo package Jobs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'

        # - name: Get npm root
        #   run: sudo npm root -g

        # - run: npm ci

        # - name: Install underpost cli
        #   run: sudo npm install -g underpost

        # usage: git remote set-url [--push] <name> <newurl> [<oldurl>]
        #    or: git remote set-url --add <name> <newurl>
        #    or: git remote set-url --delete <name> <url>
        #     --[no-]push           manipulate push URLs
        #     --[no-]add            add URL
        #     --[no-]delete         delete URLs

      - name: Install dependencies and set repo configuration
        run: |
          npm install -g underpost
          underpost config set GITHUB_TOKEN ${{ secrets.GIT_AUTH_TOKEN }}
          underpost install
          node ./bin/deploy rename-package @underpostnet/underpost
          node ./bin/deploy set-repo underpostnet/pwa-microservices-template-ghpkg

      - name: Clone github package repository
        run: |
          underpost clone --bare underpostnet/pwa-microservices-template-ghpkg
          rm -rf ./.git
          cp -rf -a ./pwa-microservices-template-ghpkg.git ./.git
          rm -rf ./pwa-microservices-template-ghpkg.git

      - name: Set git credentials
        run: |
          git config --global credential.helper ""
          git config credential.helper ""
          git config --global user.name 'underpostnet'
          git config --global user.email 'development@underpost.net'
          git config --global credential.interactive always
          git config user.name 'underpostnet'
          git config user.email 'development@underpost.net'
          git config credential.interactive always

      - name: Push to github package repository
        run: |
          pwd
          git init
          git status
          git remote set-url origin git@github.com:underpostnet/pwa-microservices-template-ghpkg.git
          git add .       
          underpost cmt . ci package-pwa-microservices-template-ghpkg 'Update github repo package'
          underpost push . underpostnet/pwa-microservices-template-ghpkg

# git clone --bare https://github.com/underpostnet/engine.git
# mkdir engine
# mv ./engine.git ./engine/.git
# cd engine
# git init

# git push -u origin https://${{ secrets.GIT_AUTH_TOKEN }}@github.com/underpostnet/pwa-microservices-template-ghpkg.git
# git push -u origin master
