name: CD | Test api rest deployment
on: [push]
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  pwa-microservices-template:
    if: github.repository == 'underpostnet/engine' && startsWith(github.event.head_commit.message, 'cd(api-rest-engine)')
    name: Remote API REST deployment
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    container:
      image: quay.io/rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: |
          dnf install -y sudo tar gzip bzip2 git
          dnf install -y curl --allowerasing

      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_24.x | bash -
          dnf install nodejs -y

      - name: Install dependencies
        run: |
          npm install
